### ISSUE TITLE
getting error dnn libaray is not found

### ISSUE THREAD

**Issue by pulkitmehtaworkmetacube** [rash1993/movie-asd#3]
While trying to run on my video , getting below error . Cuda version is 11.7. Please check . 

2023-12-15 14:08:10.099963: W tensorflow/core/framework/op_kernel.cc:1839] OP_REQUIRES failed at conv_ops_impl.h:1199 : UNIMPLEMENTED: DNN library is not found.
Traceback (most recent call last):
  File "/home/ec2-user/lmc/movie-asd/src/main.py", line 45, in <module>
    preprocessor.prep()
  File "/home/ec2-user/lmc/movie-asd/src/preprocessor.py", line 149, in prep
    self.videoPrep.run()
  File "/home/ec2-user/lmc/movie-asd/src/video_prep/video_preprocessing.py", line 225, in run
    self.getFaceTrackEmbeddings()
  File "/home/ec2-user/lmc/movie-asd/src/video_prep/video_preprocessing.py", line 80, in getFaceTrackEmbeddings
    self.faceTrackFeats = self.embeddingsExtracter.extractEmbeddings(faceTracksList)
  File "/home/ec2-user/lmc/movie-asd/src/video_prep/vggFace2_embeddings.py", line 55, in extractEmbeddings
    cropFeats = image_encoding(vggFace2Model, crops)
  File "/home/ec2-user/lmc/movie-asd/src/../Keras_VGGFace2_ResNet50/src/wrapper.py", line 42, in image_encoding
    f = model.predict(im_array, batch_size=BATCH_SIZE)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/keras/src/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/ec2-user/.local/lib/python3.9/site-packages/tensorflow/python/eager/execute.py", line 53, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.UnimplementedError: Graph execution error:

Detected at node model/conv1/7x7_s2/Conv2D defined at (most recent call last):
  File "/home/ec2-user/lmc/movie-asd/src/main.py", line 45, in <module>

  File "/home/ec2-user/lmc/movie-asd/src/preprocessor.py", line 149, in prep

  File "/home/ec2-user/lmc/movie-asd/src/video_prep/video_preprocessing.py", line 225, in run

  File "/home/ec2-user/lmc/movie-asd/src/video_prep/video_preprocessing.py", line 80, in getFaceTrackEmbeddings

  File "/home/ec2-user/lmc/movie-asd/src/video_prep/vggFace2_embeddings.py", line 55, in extractEmbeddings

  File "/home/ec2-user/lmc/movie-asd/src/../Keras_VGGFace2_ResNet50/src/wrapper.py", line 42, in image_encoding

  File "/home/ec2-user/.local/lib/python3.9/site-packages/keras/src/utils/traceback_utils.py", line 65, in error_handler

  File "/home/ec2-user/.local/lib/python3.9/site-packages/keras/src/engine/training.py", line 2655, in predict

  File "/home/ec2-user/.local/lib/python3.9/site-packages/keras/src/engine/training.py", line 2440, in predict_function

  File "/home/ec2-user/.local/lib/python3.9/site-packages/keras/src/engine/training.py", line 2425, in step_function

  File "/home/ec2-user/.local/lib/python3.9/site-packages/keras/src/engine/training.py", line 2413, in run_step

  File "/home/ec2-user/.local/lib/python3.9/site-packages/keras/src/engine/training.py", line 2381, in predict_step

  File "/home/ec2-user/.local/lib/python3.9/site-packages/keras/src/utils/traceback_utils.py", line 65, in error_handler

  File "/home/ec2-user/.local/lib/python3.9/site-packages/keras/src/engine/training.py", line 590, in __call__

  File "/home/ec2-user/.local/lib/python3.9/site-packages/keras/src/utils/traceback_utils.py", line 65, in error_handler

  File "/home/ec2-user/.local/lib/python3.9/site-packages/keras/src/engine/base_layer.py", line 1149, in __call__

  File "/home/ec2-user/.local/lib/python3.9/site-packages/keras/src/utils/traceback_utils.py", line 96, in error_handler

  File "/home/ec2-user/.local/lib/python3.9/site-packages/keras/src/engine/functional.py", line 515, in call

  File "/home/ec2-user/.local/lib/python3.9/site-packages/keras/src/engine/functional.py", line 672, in _run_internal_graph

  File "/home/ec2-user/.local/lib/python3.9/site-packages/keras/src/utils/traceback_utils.py", line 65, in error_handler

  File "/home/ec2-user/.local/lib/python3.9/site-packages/keras/src/engine/base_layer.py", line 1149, in __call__

  File "/home/ec2-user/.local/lib/python3.9/site-packages/keras/src/utils/traceback_utils.py", line 96, in error_handler

  File "/home/ec2-user/.local/lib/python3.9/site-packages/keras/src/layers/convolutional/base_conv.py", line 290, in call

  File "/home/ec2-user/.local/lib/python3.9/site-packages/keras/src/layers/convolutional/base_conv.py", line 262, in convolution_op

DNN library is not found.
         [[{{node model/conv1/7x7_s2/Conv2D}}]] [Op:__inference_predict_f

**Comment by rash1993** [comment]
It may be the case that CUDNN is not in your library path. Try adding your CUDA lib path to `LD_LIBRARY_PATH`!
